name: "publish"

on:
    push:
        branches:
            - master

jobs:
    publish-tauri:
        environment: production
        permissions:
            contents: write
        strategy:
            fail-fast: true
            matrix:
                platform: [windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: Cache Node.js modules
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Cache Rust cargo registry
              uses: actions/cache@v3
              with:
                path: ~/.cargo/registry
                key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}-cargo-registry-
                  
                        - name: Cache Rust cargo index
            - uses: actions/cache@v3
              with:
                path: ~/.cargo/index
                key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}-cargo-index-

            - name: Cache Rust cargo build
              uses: actions/cache@v3
              with:
                path: target
                key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}-cargo-build-

            - name: Install dependencies (Ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Install frontend dependencies
              run: npm install

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  tagName: mia-v__VERSION__
                  releaseName: "Mia v__VERSION__"
                  releaseBody: "See the assets to download this version and install."
                  releaseDraft: false
                  prerelease: false
